language: cpp
compiler: gcc
sudo: required
dist: trusty

notifications:
  email: false

matrix:
  include:
    # hack to get proper bionic images
    # no install step, but works with docker
    - env: BIONIC=1 ARCH=x86_64
      services:
        - docker
      install:
      script: bash -ex travis/travis-bionic.sh
    - env: BIONIC=1 ARCH=i386
      services:
        - docker
      install:
      script: bash -ex travis/travis-bionic.sh
    - env: BIONIC= ARCH=x86_64
      addons:
        apt:
          update: true
          packages:
            - qtbase5-dev
            - qt5-qmake
            - libqt5core5a
            - libqt5gui5
            - libcurl4-openssl-dev
            - libqt5widgets5
            - librsvg2-bin
            - libfuse-dev
            - desktop-file-utils
            - ccache
            - rpm
            - libcurl3
            - libbsd-dev
    - env: BIONIC= ARCH=i386
      addons:
        apt:
          update: true
          packages:
            - gcc-multilib
            - g++-multilib
            - libfuse2:i386
            - qtbase5-dev:i386
            - qt5-qmake:i386
            - qtbase5-dev-tools:i386
            - qttools5-dev-tools:i386
            - libqt5core5a:i386
            - libqt5gui5:i386
            - libcurl4-openssl-dev:i386
            - libqt5widgets5:i386
            - librsvg2-bin:i386
            - libfuse-dev:i386
            - desktop-file-utils
            - ccache
            - rpm
            - libcurl3:i386
            - libbsd-dev:i386
            - libglib2.0-dev:i386
            - liblzma-dev:i386
            - libgtest-dev
            - libcairo-dev:i386
            - libgl1-mesa-dev:i386
            - libglu1-mesa-dev:i386
            - libpng-dev:i386
            - libfontconfig1-dev:i386
            - libfreetype6-dev:i386
            - libarchive-dev:i386

install:
  - ccache -M 5G
  #- source /opt/qt*/bin/qt*-env.sh

script:
  - bash -ex travis/travis-build.sh

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - if [ "$BIONIC" == "" ]; then bash upload.sh AppImageLauncher*.AppImage* appimagelauncher*.{deb,rpm}* appimagelauncher*.tar*; fi
  - if [ "$BIONIC" != "" ]; then bash upload.sh appimagelauncher*.deb*; fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
