language: cpp
compiler: gcc
sudo: required
dist: trusty

notifications:
  email: false

install:
  - sudo apt-get update
  #- sudo apt-get -y install qt510base librsvg2-bin libfuse-dev desktop-file-utils ccache
  - sudo apt-get -y install qtbase5-dev qmake-qt5 libqt5core5a libqt5gui5 libcurl4-openssl-dev libqt5widgets5 librsvg2-bin libfuse-dev desktop-file-utils ccache rpm libcurl3 libbsd-dev
  - ccache -M 5G
  #- source /opt/qt*/bin/qt*-env.sh

script:
  - bash -ex travis/travis-build.sh

# hack to get proper bionic images
# no install step, but works with docker
matrix:
  include:
    - env: BIONIC=
    - env: BIONIC=1
      services:
        - docker
      install:
      script: bash -ex travis/travis-bionic.sh

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - if [ "$BIONIC" == "" ]; then bash upload.sh AppImageLauncher*.AppImage* appimagelauncher*.{deb,rpm}* appimagelauncher*.tar*; fi
  - if [ "$BIONIC" != "" ]; then bash upload.sh appimagelauncher*.deb*; fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
